[package]
name = "mantissa"
version = "3.3.0"
authors = ["Jeremy Wright <jtheardw@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
opt-level = 3
debug = true
