[package]
name = "mantissa"
version = "2.1.1"
authors = ["Jeremy Wright <jtheardw@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"

[profile.release]
debug = true
